package com.example.notificationtest;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.NotificationCompat;
import androidx.core.app.NotificationManagerCompat;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    Button btnNotify;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        btnNotify = findViewById(R.id.button);

        btnNotify.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                NotificationCompat.Builder builder = new NotificationCompat.Builder(getApplicationContext(), "NTF1");
                builder.setContentTitle("Notification 01");
                builder.setContentText("Please be notified that notification 01 has been triggered.");
                builder.setSmallIcon(R.drawable.ic_launcher_foreground);
                builder.setAutoCancel(true);
                builder.setPriority(NotificationCompat.PRIORITY_MAX);

                // Extended view text
                NotificationCompat.BigTextStyle bigText = new NotificationCompat.BigTextStyle();
                bigText.setBigContentTitle("Notification 01");
                bigText.setSummaryText("Please be notified that notification 01 has been triggered.");
                bigText.bigText("Hello everyone, please be noted that a new notification has been generated by the app NotificationTest. This is just a test, don't be scared. Taj is creating this app just to try out and teach in class.");
                builder.setStyle(bigText);

                // Set tap activity
                Intent intent = new Intent(getApplicationContext(), RootActivity.class);
                PendingIntent pendingIntent = PendingIntent.getActivity(getApplicationContext(), 0, intent, 0);
                builder.setContentIntent(pendingIntent);

                // Set action buttons
                builder.addAction(R.drawable.ic_launcher_background, "Response", pendingIntent);

                Notification notification = builder.build();

                NotificationManager manager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);

                if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    NotificationChannel channel = new NotificationChannel("NTF1", "General Notification", NotificationManager.IMPORTANCE_HIGH);
                    manager.createNotificationChannel(channel);
                }

                manager.notify(1, notification);
            }
        });
    }
}